### ISSUE TITLE
Difficulty in running Mmseqs2 and the others after the Roary results

### ISSUE THREAD

**Issue by Ekuufire-30** [hoelzer-lab/ribap#61]
nextflow run hoelzer-lab/ribap -r 1.0.0 --fasta "/home/emma/campy/project_campy/sequences/fasta/*fasta"

Please after changing to the above command on conda to suit my profile. I am not still able to run the program on for my genomes. I would be grateful if you could assist in this regard. Really need this to finish up my  project.

I keep getting the error message below.
Thanks

ERROR ~ Error executing process > 'RIBAP:mmseqs2'

Caused by:
  Process `RIBAP:mmseqs2` terminated with an error exit status (127)

Command executed:

  mkdir mmseq2
  cat *.faa > mmseq2/all_proteins.fa
  MMSEQDB="mmseq2/mmseq2.db"

  #Creating DB
  mmseqs createdb mmseq2/all_proteins.fa $MMSEQDB
  #Creating Index#
  mmseqs createindex --threads 4 $MMSEQDB mmseq2/tmp
  #Starting MMSeqs2 Search
  mmseqs search --threads 4 $MMSEQDB $MMSEQDB "${MMSEQDB%.*}_result" mmseq2/tmp -a
  #Converting results
  mmseqs convertalis --format-output "query,target,pident,alnlen,mismatch,gapopen,qstart,qend,qlen,tstart,tend,tlen,qcov,tcov,evalue,bits" --threads 4 $MMSEQDB $MMSEQDB "${MMSEQDB%.*}_result" "${MMSEQDB%.*}_result.csv"

  cat "${MMSEQDB%.*}_result.csv" | awk '{if($3>0.6 && $13>0.4){print $0}}' > "${MMSEQDB%.*}_result_filtered.csv"

  mv mmseq2/mmseq2_result.csv .
  mv mmseq2/mmseq2_result_filtered.csv .

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 7: mmseqs: command not found

Work dir:
  /home/emma/campy/project_campy/sequences/fasta/work/cc/447c10355d60b401a08a80509c8266

**Comment by hoelzer** [comment]
Hey @Ekuufire-30 

It seems that `mmseqs2` is not installed which should either happen via `conda` or `docker`/`singularity` depending on your setup and the used `-profile`. 

Also you could try the latest release version. And **use single tick symbols** to input multiple files! Otherwise nextflow will only read the first FASTA. Please also read [the manual](https://github.com/hoelzer-lab/ribap) carefully before starting the pipeline. 

Then, you can try:

```bash
nextflow pull hoelzer-lab/ribap
nextflow run hoelzer-lab/ribap -r 1.0.3 --fasta '/home/emma/campy/project_campy/sequences/fasta/*fasta' -profile local,conda
```

However, I recommend `docker` instead of `conda`, if that is possible for you. It seems you are running the pipeline on a local machine? A laptop or workstation? If so, you might have the permission to install `Docker.` However, you can also first try via `-profile local,conda` as suggested above.

**Comment by hoelzer** [comment]
When the other steps worked before `mmseqs`, the problem might be really just the use of the single ticks instead of double quotes...

**Comment by Ekuufire-30** [comment]
Hello @hoelzer 
Your recommendations did the magic! I am so grateful for the assistance. I used the latest version of ribap and install all the other requirements and boom it worked.
Thanks, 
Emmanuel

**Comment by hoelzer** [comment]
Great! Glad to hear. Please also check our recent paper in Genome Biology for further details (and limitations) of RIBAP. 

Cheers,
Martin
